# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled vikas_panchal87 e.g., [user1, user2]
patreon: # Replace with a single Patreon vikas_panchal87
open_collective: # Replace with a single Open Collective vikas_panchal87
ko_fi: # Replace with a single Ko-fi vikas_panchal87
tidelift: # Replace with a single Tidelift platform-name/package-vikas panchal e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-vikas panchal e.g., cloud-foundry
liberapay: # Replace with a single Liberapay vikas_panchal87
issuehunt: # Replace with a single IssueHunt vikas_panchal87
otechie: # Replace with a single Otechie vikas_panchal87
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-vikas  e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
